### ISSUE TITLE
Propagating aesthetics from `@ggplot()` to geoms.

### ISSUE THREAD

**Issue by kdpsingh** [TidierOrg/TidierPlots.jl#10]
In the original Tidier.jl issue, we had talked about the need for aesthetics to propagate from `@ggplot()` to individual geoms without generating a "missing aesthetics" error. I'm not sure if this has been implemented yet - just posting it here as a reminder to us.

This will make the 3rd example in the README with `@geom_point()` and `@geom_smooth()` a bit cleaner and easier.

**Comment by rdboyes** [comment]
This is already implemented! The aes check now happens here https://github.com/TidierOrg/TidierPlots.jl/blob/524c3c9e758b95086833cb6f0a3f7091479a80c5/src/TidierPlots.jl#L99, after ggplot aes propogation
