### ISSUE TITLE
add geom_bar options for position "stack" and "dodge"  

### ISSUE THREAD

**Issue by rdboyes** [TidierOrg/TidierPlots.jl#11]
Right now geom_bar plots the bars over top of each other - this is almost never the desired behaviour and shouldn't be the default. The current default behaviour should be called "none" and the default should be "dodge"

**Comment by kdpsingh** [comment]
Can we make "stack" the default to be consistent with ggplot2?

**Comment by rdboyes** [comment]
resolved in https://github.com/TidierOrg/TidierPlots.jl/commit/a53d5d71c4bf10582b691d1a19f1d9540edebc66
