### ISSUE TITLE
Issue with facet_wrap() Functionfacet_wrap(variable)

### ISSUE THREAD

**Issue by mathutopia** [TidierOrg/TidierPlots.jl#115]
**Describe the bug**
Hello,

I'm encountering an issue with the `facet_wrap()` function when using the TidierPlots package. I've noticed that when I apply `facet_wrap()` to a plot, it causes the plot to malfunction.

![截图_选择区域_20240908102431](https://github.com/user-attachments/assets/0ef30a7c-5ebf-416e-b3e3-e119fb28ecf4)

**Comment by kdpsingh** [comment]
Can you try `facet_wrap(:variable)`?

**Comment by mathutopia** [comment]
Thank you for your prompt response. I have tried the following code and encountered errors. For specific errors, please refer to the attached PDF document.




```julia

facet_wrap(:variable)

facet_wrap(facets="variable")

```




在 2024-09-08 21:49:05，"Karandeep Singh" ***@***.***> 写道：

Can you try facet_wrap(:variable)?

**Comment by mathutopia** [comment]
[issue.pdf](https://github.com/user-attachments/files/16924298/issue.pdf)

**Comment by rdboyes** [comment]
I can fix this - as a temporary solution, the graph should work if you set explicit limits with `lims` for y

**Comment by rdboyes** [comment]
This is fixed in the latest dev version - will be working as of 0.8.0 release (soon!)
