### ISSUE TITLE
aes(color=category) doesn't work with geom_line

### ISSUE THREAD

**Issue by taigua** [TidierOrg/TidierPlots.jl#116]
**Describe the bug**
aes(color=category) doesn't work with geom_line

**To Reproduce**
```julia
using Tidier

df = DataFrame(x = 1:6, y = [1, 6, 2, 5, 3, 4], cs = repeat(["a", "b"], 3));
ggplot(df, aes(x = :x, y = :y, color = :cs)) + geom_line()

```
**Expected behavior**
Two lines with different color.

**Screenshots**
![display](https://github.com/user-attachments/assets/18c6bdd5-405a-49ae-be03-a34a33ef02b4)

**Additional context**
  [336ed68f] CSV v0.10.14
  [13f3f980] CairoMakie v0.12.9
  [a93c6f00] DataFrames v1.6.1
  [e9467ef8] GLMakie v0.10.9
  [a59fdf5c] GenieFramework v2.3.0
  [add582a8] MLJ v0.20.7
  [5fb14364] OhMyREPL v0.5.28
  [c3e4b0f8] Pluto v0.19.46
  [295af30f] Revise v3.5.18
  [340e8cb6] SearchLight v2.11.0
  [2cb19f9e] StatsKit v0.3.1
  [f0413319] Tidier v1.4.0
⌅ [86993f9b] TidierDB v0.1.9

**Comment by rdboyes** [comment]
Thanks for reporting this - it is fixed in 0.8.0 (still in dev but coming soon!)
