### ISSUE TITLE
geom_line lines are not colored

### ISSUE THREAD

**Issue by floswald** [TidierOrg/TidierPlots.jl#125]
**Describe the bug**
I encounter a strange behaviour of `geom_line` where lines are not colored according to the `aes(color=...)`. I have not been able to reproduce with your Penguins data. So I attach the sample I have used.

**To Reproduce**

```julia
 using DataFrames
 using CSV
using CairoMakie
using TidierPlots

 x = CSV.read("sample.csv", DataFrame)

# color only for points
ggplot(x) +
           geom_point(@aes(x = year, y = value, color = variable)) +
           geom_line(@aes(x = year, y = value, color = variable))

# no color on lines
ggplot(x) +
           geom_line(@aes(x = year, y = value, color = variable))
```

**Expected behavior**
I expected the three lines to have differnt colors.

**Screenshots**
[sample.csv](https://github.com/user-attachments/files/17072533/sample.csv)

<img width="1120" alt="Screenshot 2024-09-20 at 10 47 11" src="https://github.com/user-attachments/assets/3ca2c342-fce7-49cd-80f0-1108c7712af9">

<img width="1120" alt="Screenshot 2024-09-20 at 10 47 22" src="https://github.com/user-attachments/assets/d8ff75fd-c4ff-40ed-b4f8-9d5627613686">

**Additional context**
Paste the output of `Pkg.status()` here:

```
(makie) pkg> st
Status `~/git/NumericalMethods/notebooks/makie/Project.toml`
⌃ [336ed68f] CSV v0.10.13
⌅ [13f3f980] CairoMakie v0.11.9
  [a93c6f00] DataFrames v1.6.1
⌃ [033835bb] JLD2 v0.4.46
⌃ [337ecbd1] TidierPlots v0.7.6
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated`
```

**Comment by floswald** [comment]
I tried to do `] up` but there seems to be a constraint in my env, as nothing updated. Can you spot anything there? Thanks a lot

**Comment by rdboyes** [comment]
Are you on an old version of julia? Anything older than 1.9 likely won't work

**Comment by floswald** [comment]
I removed Makie as a direct project dependency and deleted the Manifest. now i'm up to latest version and everything works. sorry about the noise... :shrug:

**Comment by rdboyes** [comment]
No problem! Let me know if you run into any other issues
