### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by rdboyes** [TidierOrg/TidierPlots.jl#14]
Need to add Documenter.jl style documentation as Tidier.jl has done

**Comment by drizk1** [comment]
Using the template that Lazaro created for the others, I have put together most of what is needed for tidierplots.. for the user guides / examples do you want me to drop in the read me essentially? Or try to make a few different pages for different aspects (dif plot types lims labs etc)?

**Comment by rdboyes** [comment]
For now, I think the readme is ok. I originally started making the readme to follow the algebraofgraphics tutorial (https://aog.makie.org/stable/generated/penguins/) but still haven't quite implemented everything that it needs. If you want to expand further than that go ahead though!

**Comment by rdboyes** [comment]
Hey @drizk1 - what's the status of this? No pressure, just don't want to duplicate work. Also I changed the interface a bit in the most recent version - I can take a look and update?

**Comment by drizk1** [comment]
Incredible update recently. Wow.

Yea that sounds good, I didn't get too far before a month off the grid and a month of applications, but this branch should have all of the files that it needs to have the documentation (based on the other Tidier____ doc sites), but it does not have the latest update.

https://github.com/drizk1/TidierPlots.jl/tree/docs_plots

**Comment by kdpsingh** [comment]
@drizk1 do you want to file a PR with this code? Maybe @rdboyes can use Git Pull to update the PR from main (or happy to help as well).

**Comment by drizk1** [comment]
just PRed!

**Comment by rdboyes** [comment]
Thanks! I edited the supported functions file so that it uses the updated syntax. The thing I'm not clear on though (I've never set up documenter.jl before) is - should this go in to the main branch? It seems like the documentation is supposed to be on a separate gh-pages branch

**Comment by kdpsingh** [comment]
Merge to main, and then as long as the TagBot for Documenter.jl is set up, it will create and commit to the gh-pages branch. Then in GitHub settings will need to let GitHub know that the gh-pages branch is where the documentation will reside.

**Comment by rdboyes** [comment]
I did this, but it doesn't seem to be working correctly... I'll try to troubleshoot on the weekend

**Comment by rdboyes** [comment]
this is now working!
