### ISSUE TITLE
Feature request @facet_grid and @facet_wrap

### ISSUE THREAD

**Issue by dpabon** [TidierOrg/TidierPlots.jl#21]
Hi,

Thanks for the wonderful work with the package! I wondered if you have plans to include facets functionality.

Cheers,
Daniel

**Comment by rdboyes** [comment]
I do - they're a little trickier to implement than you might think at first glance, but I plan to implement them eventually. If anyone wants to give this a go, the equivalent AoG functionality is through a mapping() layer with row and col kwargs

**Comment by rdboyes** [comment]
Initial implementation of this feature is complete!

```
@ggplot(penguins) + @geom_point(aes(x = bill_length_mm, y = bill_depth_mm)) + @facet_grid(rows = species, cols = island)
```
![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/0482c544-d958-44d2-800b-de569dae135b)

```
@ggplot(penguins) + @geom_point(aes(x = bill_length_mm, y = bill_depth_mm)) + @facet_wrap(species)
```

![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/a41cb39b-5b09-40e1-bbc1-e1c65adec4ff)
