### ISSUE TITLE
Error executing examples

### ISSUE THREAD

**Issue by tobi-lipede-mappa** [TidierOrg/TidierPlots.jl#23]
Not sure whether I'm doing something wrong, but I can't seem to generate any plots. 
I get an error saying the DataFrame isn't defined, e.g.:

```julia
using TidierPlots
using DataFrames
using PalmerPenguins

penguins = dropmissing(DataFrame(PalmerPenguins.load()))

@ggplot(data = penguins) + 
    @geom_bar(aes(x = species)) +
    @labs(x = "Species")

# UndefVarError: `penguins` not defined
```

**Comment by rdboyes** [comment]
This code works as written for me. Are you sure you're executing the line `penguins = dropmissing(DataFrame(PalmerPenguins.load()))`? This line should create the penguins dataset

**Comment by TLipede** [comment]
I am. If it helps at all, I was running Julia 1.10-beta2 on Pluto

**Comment by tobi-lipede-mappa** [comment]
I am. If it helps at all, I was running Julia 1.10-beta2 on Pluto

**Comment by tobi-lipede-mappa** [comment]
Confirmed it does work in the REPL

**Comment by rdboyes** [comment]
ok - the issue is likely to do with how the environment is chosen for the call to Base.eval inside of pluto. I will take a look and see if I can fix it - in the meantime, a work-around if you want it is to use the AoG compatibility shown in the final example in the readme

**Comment by TLipede** [comment]
Thank you for your help! Will do

**Comment by tobi-lipede-mappa** [comment]
Thank you for your help! Will do

**Comment by rdboyes** [comment]
I looked into this and was able to reproduce the error, but I can't figure out what's causing it. @kdpsingh any ideas?

**Comment by kdpsingh** [comment]
Thanks for tagging me. I'll look into it also.

**Comment by rdboyes** [comment]
The weird thing is that if I create new macros inside the notebook - like define `@ggplot_pluto` and `@geom_point_pluto` without changing anything about them, they work as expected. The issue might be something to do with how Pluto manages modules?

**Comment by kdpsingh** [comment]
This is probably a scoping issue related to the use of `eval()` in the package, but I haven't yet had a chance to actually try it out to see what the error is.

**Comment by rdboyes** [comment]
It might be possible to refactor a bit and remove the `eval` calls - I had intended to do that eventually anyway

**Comment by rdboyes** [comment]
I realized as I was trying to refactor the `eval` calls out that the package actually barely needs macros at all. I have a working version in this branch https://github.com/TidierOrg/TidierPlots.jl/tree/no-eval that only uses one macro (`@aes`) and even that can be replaced with a function if you're willing to use strings for column selection ...

**Comment by rdboyes** [comment]
This issue is resolved as of version 0.4.0!
![Screenshot 2023-09-28 175940](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/61c12e0c-2dbb-4845-8677-4fa0f954cf20)

**Comment by kdpsingh** [comment]
If it works without macros, that's great! Even if you're using macros, there's no need to do any evaluation. If you return a quoted expression from a macro, the resulting expression automatically gets evaluated in the user's scope.

So if for any reason we need to go back to using macros, happy to help remove the evaluation piece.

**Comment by kdpsingh** [comment]
Does this work in Pluto now?

**Comment by kdpsingh** [comment]
Nevermind, I see from the screenshot that it does!
