### ISSUE TITLE
Automatic handling of missing values

### ISSUE THREAD

**Issue by christophscheuch** [TidierOrg/TidierPlots.jl#24]
For those stats which require complete data, missing values will be automatically removed with a warning in ´ggplot2´ (see [here](https://ggplot2.tidyverse.org/reference/remove_missing.html) for the corresponding convenience function). The Python library `plotnine` also removes missing values with a warning.  When I started creating plots with `TidierPlots`, I was confused by the axis labels until I realized that it automatically adds a `missing ` category to the labels. 

Here is a specific example:
```
using Tidier, PalmerPenguins

penguins = DataFrame(PalmerPenguins.load())

# Creating a plot without dropping missing variables leads to messed up axis labels
@ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  @geom_point()

# Dropping missing values from aes variables leads to proper labels
penguins_sub = @drop_na(penguins, bill_length_mm, bill_depth_mm)
@ggplot(penguins_sub, aes(x = bill_length_mm, y = bill_depth_mm)) +
  @geom_point()
```

Is this desired behavior or do we also want to have automatic handling of missing values eventually?

**Comment by rdboyes** [comment]
fixed in https://github.com/TidierOrg/TidierPlots.jl/commit/2c45592dce2de56cb4e34542180af42683dc2e9c
