### ISSUE TITLE
Feature request for `@geom_density` macro

### ISSUE THREAD

**Issue by christophscheuch** [TidierOrg/TidierPlots.jl#25]
Would be great if we could also create density plots as they are part of the basic visualization types in [R4DS](https://r4ds.hadley.nz/data-visualize.html#a-numerical-variable).

I guess it is a fairly low hanging fruit because `AlgebraOfGraphics.jl` provides the [density function](https://docs.juliahub.com/AlgebraOfGraphics/CHIaw/0.4.7/generated/datatransformations/#Density).

Here are some hypothetical examples:
```
using Tidier, PalmerPenguins
penguins = DataFrame(PalmerPenguins.load())

@ggplot(penguins, aes(x = body_mass_g)) +
  @geom_density()

@ggplot(penguins, aes(x = body_mass_g, color = species, fill = species)) +
  @geom_density(linewidth = 0.75, alpha = 0.5)
```

**Comment by rdboyes** [comment]
This is added - and adding new geoms that are supported in AoG really is low hanging fruit if anyone wants to try! See commit https://github.com/TidierOrg/TidierPlots.jl/commit/ecfc96f5eb609f8d2d059670dbcaa0224efe3ce9 for all the code that was required to add this functionality :) 

```
@ggplot(penguins, aes(x = body_mass_g, color = species, fill = species)) +
  @geom_density(linewidth = 0.75, alpha = 0.5)
```

![plot_3](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/28687ab8-d458-4573-880e-2ecd8ff9fb57)

**Comment by kdpsingh** [comment]
That's pretty amazing that it's so straightforward to add a geom on top of what you've already built.

Okay if I update the version and release to the registry?

**Comment by rdboyes** [comment]
Yep! I fixed the automatic missing value handling as well from issue https://github.com/TidierOrg/TidierPlots.jl/issues/24
