### ISSUE TITLE
geoms relying on density() are broken

### ISSUE THREAD

**Issue by rdboyes** [TidierOrg/TidierPlots.jl#35]

**Comment by joshualeond** [comment]
FYI, I believe I'm running into this as well: `ERROR: Tuple field type cannot be Union{}`

**Comment by rdboyes** [comment]
Yep - I get the same error when I run the equivalent algebra of graphics code though. Are you on 1.10-beta3?

**Comment by joshualeond** [comment]
Yes, I'm on `1.10.0-beta3`, I haven't tried the AlgebraOfGraphics code yet. I see your issue on that side though: https://github.com/MakieOrg/AlgebraOfGraphics.jl/issues/472 

I'll keep an eye out on that one. Thanks!

**Comment by kdpsingh** [comment]
Hi @rdboyes, it looks like this hasn't been fixed on the AoG side since the issue is still open. Once Julia 1.10 lands, does that mean this package won't work for calculating/plotting densities?

(I assume so, just seeing if we can get the Makie/AoG folks to take a look)

**Comment by rdboyes** [comment]
As far as I can tell, yes, that's what it means. AoG's density function won't work in 1.10 and so our calls to it won't work either. I assume AoG is going to get a major rewrite for compatibility with Makie's declarative API so they aren't updating the current code anymore

**Comment by rdboyes** [comment]
This is now fixed thanks to an update to AoG
