### ISSUE TITLE
TidierPlot as part of a chain

### ISSUE THREAD

**Issue by ymer** [TidierOrg/TidierPlots.jl#38]
In Tidyverse you can use ggplot as part of a chain. (Example below.) Is this possible with TidierPlots?

```
df <- tibble(
  age = c(25, 30, 35),
  score = c(90, 85, 88)
)

df |> 
  mutate(score = score * 2) |> 
  ggplot(aes(x = age, y = score)) +
  geom_point()
```

**Comment by kdpsingh** [comment]
Yes, you can do this with Tidier. We actually decided to make it so that ggplot functions can be chained together EITHER using `+` or with pipes, so if you're in the middle of a pipe, you can just stick with the piped syntax. The following code should work (though I haven't tested to confirm).

```julia
using TidierData, TidierPlots

df = DataFrame(
  age = [25, 30, 35],
  score = [90, 85, 88]
)

@chain df begin
  @mutate(score = score * 2)
  ggplot(@aes(x = age, y = score))
  geom_point()
end
```

**Comment by kdpsingh** [comment]
I'll close the issue for now. Feel free to re-open if needed.
