### ISSUE TITLE
Differences in behaviour between the ggplot and tidier implementations of `geom_bar()` and `geom_col()`.

### ISSUE THREAD

**Issue by JasonPekos** [TidierOrg/TidierPlots.jl#40]
Looking at the [R bar plot documentation](https://ggplot2.tidyverse.org/reference/geom_bar.html), there are significant differences between the Julia and R bar plot implementations. Some of these — related to sideways bar plots — are pretty significant. 

---

Consider the following ggplot (R) code:

```R
ggplot(mpg) + geom_bar(aes(y = class))
```
![geom_bar-3](https://github.com/TidierOrg/TidierPlots.jl/assets/78766845/be03669b-a130-40b2-a97e-af0a4e83c58a)

The corresponding Julia code seems like it should be:

```Julia
using RDatasets
using TidierPlots

cars = dataset("datasets", "mtcars")

ggplot(cars) + 
    geom_bar(@aes(y = Model))
```

But Tidier fails here, requiring an `x` aesthetic. 

`geom_col()` is a little weirder. In R:

```R
ggplot(mpg, aes(y = class, x = cyl)) + geom_col()
```
![g](https://github.com/TidierOrg/TidierPlots.jl/assets/78766845/35c58d25-a0cb-4eee-b7a1-0f36bceb0965)

However in TidierPlots:

```Julia
ggplot(cars) + 
    geom_col(@aes(y = Model, x = Cyl))
```
![plot_147](https://github.com/TidierOrg/TidierPlots.jl/assets/78766845/d67fb2b5-c4c7-4ddc-ba74-2b7916f522a8)

I think at least the `geom_col` behaviour is concerning.

**Comment by rdboyes** [comment]
Finally making progress on this issue - in 0.6 (not released yet): 

```
using TidierPlots
using DataFrames

df = DataFrame(cat = ["left", "left", "left",
 "middle", "middle", "middle", "right", "right", "right"],
       height = 0.1:0.1:0.9,
       grp = [1, 2, 3, 1, 2, 3, 1, 2, 3],
       grp1 = [1, 2, 2, 1, 1, 2, 1, 1, 2],
       grp2 = [1, 1, 2, 1, 2, 1, 1, 2, 1]
)

ggplot(df, yticks = (1:3, ["bottom", "middle", "top"])) + 
    geom_col(@aes(cat, height, color = grp, bar_labels = height), 
        position = "dodge", direction = "x") + labs(title = "Dodged Bars") + 
    theme_dark()
```
![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/224ca612-f28a-4fec-8fb7-a8f97689317d)

**Comment by rdboyes** [comment]
The geom_bar behaviour is fixed now, but I think the geom_col behaviour in R is actually ... bad? It's not actually clear to me what the plot in the example should look like in order to make sense. In any case: 

```
using TidierPlots
using DataFrames
using CSV
    
cars = CSV.read("scratch/auto-mpg.csv", DataFrame)
    
ggplot(cars) + 
    geom_bar(@aes(y = class))
```

Produces (in 0.6.0): 
![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/ff52b393-4052-4529-96ae-8e88776a40cd)
