### ISSUE TITLE
Facetting not working!

### ISSUE THREAD

**Issue by aelmokadem** [TidierOrg/TidierPlots.jl#41]
Hi,

Want to start by saying this is a wonderful ecosystem for Julia.

I am having an issue using facetting with TidierPlots.jl. The code below gives an error

```
using TidierPlots

df = DataFrame(x = [1,2,3,4,5,6], y = [5,6,7,8,9,0], z=["a","a","b","b","c","c"])

@ggplot(data=df, aes(x=x,y=y)) + @geom_point() + @facet_wrap(z)
```

The error:

```
ERROR: LoadError: UndefVarError: `@facet_wrap` not defined
in expression starting at /data/cytomx/svn-proj-CTM0701C/script/test.jl:5
```

What am I missing here?

**Comment by rdboyes** [comment]
I'm just cleaning up the last bits of syntax still from the change I made away from macros! 

`ggplot(data=df, @es(x=x,y=y)) + geom_point() + facet_wrap(facets = :z)` will do what you want, but I still need to update facet_wrap to take strings instead of Julia-style symbols

**Comment by rdboyes** [comment]
or - as well as Julia-style symbols, I guess

**Comment by aelmokadem** [comment]
Thank you @rdboyes  for the fast reply. This line doesn't seem to work still! Just `facet_wrap` is not recognized?!

```
@ggplot(data=df, @aes(x=x,y=y)) + @geom_point() + facet_wrap(facets = :z)
ERROR: UndefVarError: `facet_wrap` not defined
```

**Comment by rdboyes** [comment]
ggplot and geom_point are both not macros - they should not have the `@` before them

**Comment by aelmokadem** [comment]
Ok so I tried these:

```
julia> ggplot(data=df, @aes(x=x,y=y)) + geom_point() + facet_wrap(facets = :z)
ERROR: LoadError: UndefVarError: `@aes` not defined
```

```
julia> ggplot(data=df, aes(x=x,y=y)) + geom_point() + facet_wrap(facets = :z)
ERROR: UndefVarError: `x` not defined
```

so looks like I am still missing something!!

**Comment by rdboyes** [comment]
do you have the latest version installed?

**Comment by aelmokadem** [comment]
I am using TidierPlots v0.1.0 !

**Comment by rdboyes** [comment]
That’s the problem then! The latest version is 0.5.2 and facetting wasn’t present in the 0.1.0 release. If you update to the latest version it should work as expected

**Comment by aelmokadem** [comment]
Oh OK. Will try that then. Thanks again @rdboyes

**Comment by rdboyes** [comment]
No problem - I'm guessing that you installed via the Tidier metapackage? I just pushed an update that will make that package install the correct version

**Comment by aelmokadem** [comment]
Yeah I think that's the issue that the update is restricted by the Tidier package. Once the push is in effect, I think it should be all good.

**Comment by kdpsingh** [comment]
@aelmokadem It's possible that you have an old version of Tidier.jl, which accidentally restricted upgrades to base packages. If you update Tidier.jl, you should then be able to update TidierPlots.jl. I'm planning to push out a new version of Tidier.jl soon that will install the latest versions of all the base packages.

**Comment by kdpsingh** [comment]
Thanks @rdboyes. I see you pushed the latest version. One thing to keep in mind is that specifying the full version number "0.5.2" won't allow for future updates beyond 0.7. But if you specify "0.5", then it will allow for future base package updates all the way up until 1. So I may tweak this in a future update with the intent of future-proofing Tidier.jl.

**Comment by rdboyes** [comment]
Ah - my mistake. Feel free to change it to "0.5" (or I can!)
