### ISSUE TITLE
Possible complete rewrite based on Makie's new API

### ISSUE THREAD

**Issue by rdboyes** [TidierOrg/TidierPlots.jl#44]
Makie v0.20 introduces a new declarative API - AoG may be rewritten to use this, and it might be good to do that for TidierPlots as well. The API is still experimental at this point: https://docs.makie.org/stable/explanations/specapi/

**Comment by rdboyes** [comment]
I think it should be compatible still - there's just an additional "declarative" API that has been added directly to Makie in 0.20 that makes it more feasible to go straight to Makie

**Comment by kdpsingh** [comment]
Got it, thanks. In that case, we can leave our [compat] entry as-is for now. Will close this issue.
