### ISSUE TITLE
What would be the roadmap for `ggplot2` extensions?

### ISSUE THREAD

**Issue by camilogarciabotero** [TidierOrg/TidierPlots.jl#47]
Hi there,

Thank you for bringing `ggplot2` to Julia. One of the nice things, besides the fantastic and intuitive syntax of the `ggplot2` library, is the nice [ecosystem of extensions](https://exts.ggplot2.tidyverse.org/gallery/) that it has. I wanted to open the discussion about it. What would be the strategy? Is it better to extend them here? Would it be better to have a side repo/org/ to host a growing extension ecosystem of packages? What extensions could be easily ported to the ecosystem? Would it be better to let it grow organically by the community?

Best.

**Comment by kdpsingh** [comment]
Thanks @camilogarciabotero for bringing this up! Definitely one of the main strengths of R `ggplot2` are the extensions and not simply the syntax.

If you look at their ecosystem of extensions, they vary quite a bit in their scope and what they do. For example, `cowplot` is an extension intended for laying out plots and achieves a similar aim as `patchwork`. But then `ggdist` has a very different purpose, focusing on visualizing distributions for a different set of end-users. So I think it's hard to think that we could wrap all of these up into a single TidierExtensions package or even a single repository.

My guess is that we would probably hope to see some organic development from other devs, and very likely we would look to see how to more easily integrate Makie extensions into TidierPlots, as Makie (our backend) also has a growing ecosystem (https://makie.org).

Would love to hear @rdboyes's thinking on this.

**Comment by kdpsingh** [comment]
On a related note though, I think we still have a lot of work to do to make the case to both Julia and R users that the Tidier.jl ecosystem is worth learning.

My sense is that the Tidier.jl community is currently pretty small, but I'm hoping it will grow as we develop more ways for people to learn it and to hopefully appreciate its design.

**Comment by camilogarciabotero** [comment]
> If you look at their ecosystem of extensions, they vary quite a bit in their scope and what they do. 

I do agree with these point. On the other hand, there are some extensions whose functionality seems to be very tight to the `ggplot2` itself, like the `ggrepel` that avoids label overlapping. This for instance could be something that the `TidierPlots.jl` have by default in the `geom_label` method. Similarly, the [`ggraph`](https://github.com/thomasp85/ggraph) could bring some new `geoms` to be present by default.

> On a related note though, I think we still have a lot of work to do to make the case to both Julia and R users that the `Tidier.jl` ecosystem is worth learning.

Yeah, definitely the extension of the ecosystem is a very further step. However, when I do work with `ggplot2` to make an intermediate or sightlier complex plot, I tend to to load more than one extension. Could otherwise, having a supported and established ecosystem of extension, something that will bring more users to the `Tidier.jl`?

**Comment by camilogarciabotero** [comment]
Nice to hear that something similar is happening with the `TidierData.jl`. Btw, thanks for all the effort to port the `tidyverse` into Julia!

**Comment by rdboyes** [comment]
My feeling is that anything that is supported in the underlying Makie/AoG packages can be part of the main TidierPlots package. This includes a lot of notable ggplot extensions, including `patchwork` (seriously though why isn't this part of R's ggplot at this point?), `ggdist`, `gganimate`, etc. 

If it gets to the point where specific functionality is developed in TidierPlots that merits its own package we can break it off - right now "having too much functionality" is not amoung our problems in my opinion :)

**Comment by rdboyes** [comment]
Closing this issue to open separate issues for extension implementations
