### ISSUE TITLE
Support for custom label formatting

### ISSUE THREAD

**Issue by atantos** [TidierOrg/TidierPlots.jl#48]
Hi!

First of all, kudos for the great job you are all people doing!
One of the essential features that help people make their points clearer is the support for custom label formatting. For instance, right now, the `labels` keyword argument of `scale_x_continuous()` is missing. In R, there is the `scales::percent_format()` that really makes the case. I navigated through the involved functions, such as the  `scale_template()`, `extract_aes()` and nothing suggests that something similar is present right now.

My suggestion would be to allow users to have their own custom string manipulation function, such as the one below, BUT to also have default ones such as R's `percent_format()`:

`scale_x_continuous(labels=x -> string(round(x * 100, digits=2), "%"))`

Thanks!

**Comment by rdboyes** [comment]
Definitely planning to add this! One of the tricky things about doing the translation here (and in general) is that the Makie interface "thinks" of the location of these options differently than the ggplot interface does, and in some cases treats continuous and categorical axes very differently ... it's a work in progress, but I will add this soon

**Comment by atantos** [comment]
> Definitely planning to add this! One of the tricky things about doing the translation here (and in general) is that the Makie interface "thinks" of the location of these options differently than the ggplot interface does, and in some cases treats continuous and categorical axes very differently ... it's a work in progress, but I will add this soon

Great! Thanks for your efforts! P.S.: In the past few months, I've been trying to develop use cases for tutorials on utilizing the Tidier.jl ecosystem for data analysis. However, I often encounter visualization incompatibilities like these, which is understandable considering its current level of development. Keep up the excellent work! @kdpsingh

**Comment by rdboyes** [comment]
This is starting to work! Arbitrary julia functions can now be applied to the labels: 

```
ggplot(penguins) + 
    geom_point(aes(x = :bill_depth_mm, y = :bill_length_mm, color = :species)) + 
    scale_x_continuous(labels = (x -> string.(x) .* " mm"))
```
![labels](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/a3c10585-b343-41fe-9b2c-6282c1d95b48)

Format strings will also work: 

```
g = ggplot(penguins) + 
    geom_point(aes(x = :bill_depth_mm, y = :bill_length_mm, color = :species)) + 
    scale_x_continuous(labels = "{:.3f}mm")
```
![labels](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/e542147a-1735-4bd6-bc32-8144f0ddb66b)

**Comment by atantos** [comment]
Great news!

It's about time to start getting it to work!

Alex
