### ISSUE TITLE
pkgs.genieframework.com downloads count no longer working

### ISSUE THREAD

**Issue by rdboyes** [TidierOrg/TidierPlots.jl#53]

**Comment by kdpsingh** [comment]
This is a known issue. They are in the process of securing a different server to run that service. We can close this issue. It affects every Julia package.

**Comment by kdpsingh** [comment]
See: https://discourse.julialang.org/t/julia-downloads-stats-and-julia-downloads-badges/74712/7

**Comment by rdboyes** [comment]
Will update link when server is fixed
