### ISSUE TITLE
geom_hvline functions not useable.

### ISSUE THREAD

**Issue by RijanHasTwoEars7** [TidierOrg/TidierPlots.jl#57]
For Julia 1.10.0, I am not sure why but `geom_hline` and `geom_vline` show up in tab-completion in my IDE but when I use them:

`ggplot(data) + geom_point(aes(x = :col1, y = :col2)) + geom_hline(yintercept = y-value here) `

I get the following error:
```
UndefVarError: `geom_hline` not defined

Stacktrace:
 [1] top-level scope
   @ In[101]:1
```

They show up in tab completion and I see that they have been defined here: https://github.com/TidierOrg/TidierPlots.jl/blob/main/src/geoms/geom_hvline.jl

Seems like something is finicky with my runtime.

**Comment by rdboyes** [comment]
I forgot to include the file that defines geom_hline and geom_vline - fixed in 0.5.6 (https://github.com/TidierOrg/TidierPlots.jl/commit/9864ea0ef1c464497ab7fb4d084e99bca2984e76)
