### ISSUE TITLE
Linewidth for geom_line() does not change

### ISSUE THREAD

**Issue by AdaemmerP** [TidierOrg/TidierPlots.jl#58]
Thanks for the initiative and great package(s)!

I cannot change the linewidth with `geom_line()`:

```julia
using Tidier
using DataFrames


# create data
df = DataFrame(
x = 1:1000, 
y = rand(1000)
)

# this plot ...
ggplot(data = df) +
    geom_line(aes(
        x = :x, 
        y = :y, 
        ), 
    linewidth = .05
    )

# ... looks the same as this one    
ggplot(data = df) +
    geom_line(aes(
        x = :x, 
        y = :y, 
        ),  
    linewidth = 5
    )
```
According to the `Manifest.toml` I am using `TidierPlots.jl` Version 0.5.4.

**Comment by kdpsingh** [comment]
@rdboyes Any thoughts on this?

I'm guessing linewidth may not be supported yet but wanted to ping for you to take a look when you have a chance.

**Comment by rdboyes** [comment]
Fixed with 0.5.5 (https://github.com/TidierOrg/TidierPlots.jl/commit/c3e5ed02967f5a63ebb86be4daca52066b6e39f7)!

**Comment by kdpsingh** [comment]
@AdaemmerP make sure to update TidierPlots to be able to see this update (once it hits the registry).

**Comment by AdaemmerP** [comment]
Thank you!
