### ISSUE TITLE
Plot is visualized twice in Jupyter Notebooks and Quarto html pages 

### ISSUE THREAD

**Issue by AdaemmerP** [TidierOrg/TidierPlots.jl#66]
When running the following code in a Jupyter Notebook or using Quarto (html output), the plot is shown twice. This does not occur when creating that plot in a simple .jl-file: 

```julia
using DataFrames
using Tidier

df = DataFrame(a = 1:100, b=rand(100))
@chain df begin
    ggplot(aes(x=:a, y=:b)) 
    geom_point()
end
```

**Comment by rdboyes** [comment]
Hi - this can be fixed using the option `plot_show` - specifically, do the following early in your notebook: 

```
TidierPlots_set("plot_show", false)
```

I should add a page to the documentation that explains optimal setups for various environments - thanks for reporting this!

**Comment by AdaemmerP** [comment]
Great, thanks!

**Comment by rdboyes** [comment]
added a paragraph in the readme and documentation to explain this: https://github.com/TidierOrg/TidierPlots.jl?tab=readme-ov-file#display-options-for-quarto-jupyter-and-plutojl

**Comment by pywugate** [comment]
Hi, 
I ran the rainclouds example in VSCode and still got 2 plots, 
but I got nothing after `TidierPlots_set("plot_show", true)`.

I also tried `TidierPlots_set("autoplot", false)` but got ```UndefVarError: `autoplot` not defined```

**Comment by pywugate** [comment]
I solved it.
`display(draw_ggplot(plt))`
