### ISSUE TITLE
@aes macro update to support calculated aesthetics

### ISSUE THREAD

**Issue by rdboyes** [TidierOrg/TidierPlots.jl#71]
0.6.3 added support for calculated aesthetics in the function `aes` - need to extend this feature to the macro `@aes`.

**Comment by adknudson** [comment]
Can you give an example of how to call `aes` with a calculated column? I'm trying to make sense of the function code but having trouble.

Is the goal to have something like `@aes(x = sqrt(variable))`?

**Comment by rdboyes** [comment]
Yes - e.g. this example from the R ggplot docs:
![image](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/fe4f035f-361d-4d8b-a0cb-8eaed4fb808e)

**Comment by kdpsingh** [comment]
Sorry I have been so slow on this one. If you'd like to work on it, I can outline what I think is the best way to do it in a reply to this message. Otherwise, I'm hoping to get to it soon-ish.

**Comment by rdboyes** [comment]
I know the complexity is weirdly high here - and I'm open to any rewrite suggestions. This was the simplest structure I could come up with that was also flexible enough to encode all of the possible aes requirements (look for example at `geom_contour`)

**Comment by rdboyes** [comment]
It does - what would mutate return, though? Would it be DataFrames syntax? We still have to store that and run it later, since when the aes is called, we don't necessarily have access to the DataFrame that we're referencing

**Comment by kdpsingh** [comment]
That was going to be my question. Isn't the underlying data part of the ggplot struct?

If it was, I was thinking we could create a temporary column containing the mutated result and then reference that column.

**Comment by rdboyes** [comment]
Is there an existing way to have @mutate return the code but not run it?

**Comment by kdpsingh** [comment]
Would wrapping it inside of an anonymous function work?

For example, `df -> @mutate(df, TidierPlots_x = mpg / 2)`? Here, df represents the data frame and not a column per se.

I'm still trying to wrap my head around why we couldn't modify the struct in place rather than defer the evaluation. I haven't tried it, so you definitely have a better understanding.

**Comment by rdboyes** [comment]
It's because in call like this: 

```julia
ggplot(penguins) + 
  geom_point(@aes(bill_length_mm/10, bill_depth_mm))
```

`geom_point(@aes(bill_length_mm/10, bill_depth_mm))` will evaluate to a `Geom` object with no data in it - it will only inherit the data later when you go to draw it. So there's nothing for the mutate function to immediately act on

**Comment by kdpsingh** [comment]
Got it. Another option would be to wrap it inside of an expression. We would pipe the expression through the `@mutate` when ready to draw the plot.

**Comment by rdboyes** [comment]
I've made progress on this - I was removing some of the "deep type piracy" and made it easier to implement as a consequence. Its almost working, but there's a questionable `eval` call that I think is causing some troubles - take a look here if you get a chance: https://github.com/TidierOrg/TidierPlots.jl/blob/45a102f8f83c4b81c6a36e91970537a159602644/src/aes.jl#L44

**Comment by kdpsingh** [comment]
Thanks! I will take a look at this.
