### ISSUE TITLE
Plots not displaying legends for `aes`

### ISSUE THREAD

**Issue by camilogarciabotero** [TidierOrg/TidierPlots.jl#74]
Hi all,

I was playing with `TidierPlots.jl` and noticed that the plots do not have legends. And when looking for that in the docs, I could not find any `legend()`. In `ggplot2` they are displayed by default once an `aes` is mapped to a variable:

![customized-scatter](https://github.com/TidierOrg/TidierPlots.jl/assets/25586362/315c2890-d1a3-4617-9042-b054f73f50c1)

Best!

**Comment by rdboyes** [comment]
Added to 0.8.0 release checklist - this isn't broken so much as it doesn't currently exist at all

**Comment by rdboyes** [comment]
Progress!
![image](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/663084b0-74d2-45a1-9b08-1e592db549a6)

**Comment by rdboyes** [comment]
Getting there!

```julia
ggplot(penguins) + 
           geom_line(aes(x = :bill_depth_mm, y = :bill_length_mm, colour = :species)) +
           geom_point(aes(x = :bill_depth_mm, y = :bill_length_mm, colour = :species)) +
           scale_colour_manual("red", "blue", "darkgreen")
```

![image](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/1fbe2693-8adb-4351-95ce-c973326ec14c)

**Comment by camilogarciabotero** [comment]
This is amazing!

**Comment by rdboyes** [comment]
dev version now has automatic legend creation for color (both discrete and continuous versions)! Thanks for the report - I will expand the auto-legend system as we add more scales (fill/alpha/size/etc)
