### ISSUE TITLE
UndefVarError: `transforms` not defined for `geom_vline`

### ISSUE THREAD

**Issue by adknudson** [TidierOrg/TidierPlots.jl#75]
In `geom_hline`, the first line is 

```julia
aes_dict, args_dict, transforms = extract_aes(args, kwargs)
```

whereas in `geom_vline` it is missing the transforms variable.

Are all geoms suppoised to have the `transforms` argument since it is returned by `extract_aes`? Or perhaps `geom_hline` and `geom_vline` should use the `geom_template` method? Let me know what direction to take and I'll be happy to submit a pull request fixing this issue.

**Comment by kdpsingh** [comment]
I don't know the answer to your question and will let @rdboyes weigh in. I just wanted to write to thank you for contributing, both an issue and a PR!

**Comment by rdboyes** [comment]
You're correct - I changed the extract_aes function to return `transforms` as well recently so that applying functions inside of `aes` would work. I just missed `geom_vline` when I updated the geom functions to support that! Thanks for the pull request, it looks great - I merged it
