### ISSUE TITLE
using a pipe (|>) instead of plus sign (+) for chaning geoms and layers?

### ISSUE THREAD

**Issue by camilogarciabotero** [TidierOrg/TidierPlots.jl#8]
Hi all,

This is a great idea and fantastic initiative to bring `ggplot`to Julia. I am now more confident to stick into Julia for all my code efforts. Thank you. 

I open this issue more as a discussion (which I think could be nice to open such a space for the org or the package instead), because once somebody asked Hadley (I can´t recall when and where... sorry for that) about the design of `ggplot` and he replied that it was a shame that the R pipe wasn't invented before `ggplot` otherwise they would have use it instead of the `+` for chaining the layers in their grammar. So, I know that the idea is to stick to the current syntax, but wondering if the pipe would bring more efficiency or consistency with the "Tidier" philosophy?

Thanks again!

**Comment by kdpsingh** [comment]
@rdboyes and I talked about the possibility of supporting both mechanisms (`+` and piping) here: https://github.com/TidierOrg/Tidier.jl/issues/97

It looks like may be able to handle both ways using multiple dispatch. I 100% agree that I'd probably want to use this within `@chain` macros.

**Comment by camilogarciabotero** [comment]
Oh I see, yeah. Supporting both will be a killer!

**Comment by kdpsingh** [comment]
Feel free to leave this open until implemented just as a reminder!

**Comment by kdpsingh** [comment]
Now that we have switched to a function-based interface, I feel like this may be an even easier issue to tackle using multiple dispatch.

@rdboyes, what do you think?

**Comment by rdboyes** [comment]
Yes, this is simple to add now. I have the following working already: 

```
@chain penguins begin
         ggplot
         geom_point(@es(x = bill_length_mm, y = bill_depth_mm, color = species))
       end
```
![download](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/ba76966b-623c-4ecc-bcbb-4e51f5e07c9f)

**Comment by rdboyes** [comment]
This is now fully supported for all functions (scales, geoms, labs/lims, facets) as of 0.5.0! Closing issue
