### ISSUE TITLE
Consider changing `@ggplot` data to positional argument

### ISSUE THREAD

**Issue by kdpsingh** [TidierOrg/TidierPlots.jl#9]
In general, I love the use of named arguments in the code thus far. However, we should consider changing the `data =` argument inside of `@ggplot()` only to being a positional argument rather than a named argument.

If we can get piping to work (which I'm happy to play with), this may make it easier to pipe datasets into `@ggplot()` rather than having to use a `@ggplot(data = _)` placeholder.

**Comment by rdboyes** [comment]
I think my ideal syntax for use in the chain form looks something like: 

```
@chain df begin
  ... tidier operations ...
  @ggplot aes(x = x, y = y) begin
     @geom_point(... options)
     @geom_smooth( ... options) 
     @labs(x = "xlabel")
   end
end
```

Kind of mirroring the chain syntax - is this what you're thinking? 

I have an idea for making data a "positional" argument - let me test it out

**Comment by rdboyes** [comment]
Ok this is now "half-fixed" - you can write:

```
@ggplot(penguins, aes(x = bill_length_mm, y = bill_depth_mm, color = species)) + 
    @geom_point() + 
    @geom_smooth(method = "lm")
```

And it will work. It doesn't seem to work inside of chain though ... not sure why not exactly

**Comment by rdboyes** [comment]
My hesitation to make it a true positional argument is that sometimes I write ggplot calls in R that look like: 

```
ggplot() + 
  geom_*(... data and options ...)
  geom_*(... different data and options ...) 
```

And if it's positional, you couldn't do that, I don't think? Maybe I'm wrong here though
