### ISSUE TITLE
`geom_line` with colors connects different traces

### ISSUE THREAD

**Issue by jfb-h** [TidierOrg/TidierPlots.jl#93]
If you plot different traces, the start of each trace gets connected to the next. Here's a reproducer:

```julia
df = mapreduce(vcat, 1:4) do i 
	DataFrame(
		x=collect(1:100),
		y=cumsum(randn(100)),
		g=fill(string(i), 100)
	)
end

ggplot(df, aes(x=:x, y=:y, color=:g)) + geom_line()
```

![grafik](https://github.com/TidierOrg/TidierPlots.jl/assets/61913033/7d3fc0e5-d632-4682-89e9-02aebb091701)

**Comment by rdboyes** [comment]
Thanks for reporting this - it's another problem (similar to https://github.com/TidierOrg/TidierPlots.jl/issues/86) that is downstream from the "ad hoc" way I've handled the idea of "grouping" so far in the package. Hoping to have a fix for this on the way to 0.8.0

**Comment by rdboyes** [comment]
Thanks @adknudson - this was essentially how I was imagining this would be fixed, but helpful to have a MWE. I added support for geoms that return multiple PlotSpecs when I was fixing `geom_smooth` (just need to have them return a `Vector{PlotSpec}` and they should draw automatically). All we need to do is have geoms conditionally return a vector of plotspecs when appropriate and this should work

**Comment by rdboyes** [comment]
This is working for `geom_path` in a dev branch: 

![image](https://github.com/TidierOrg/TidierPlots.jl/assets/33524191/88b46c66-e03d-40be-bb5d-ccba12504516)

`geom_line` isn't currently cooperating - the sort is conflicting with the grouping. Should be fixed soon!

**Comment by rdboyes** [comment]
`geom_line` fixed - will merge soon
